### ISSUE TITLE
Could not find com.github.yalantis:ucrop:2.2.1-native

### ISSUE THREAD

**Issue by forconz** [lvwangbeta/Poplar#8]
PS D:\Projects\Test\Poplar\Poplar2\Poplar\poplar-app> react-native run-android
Scanning folders for symlinks in D:\Projects\Test\Poplar\Poplar2\Poplar\poplar-app\node_modules (61ms)
Starting JS server...
Building and installing the app on the device (cd android && gradlew.bat installDebug)...
Incremental java compilation is an incubating feature.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > A problem occurred configuring project ':react-native-image-crop-picker'.
      > Could not resolve all dependencies for configuration ':react-native-image-crop-picker:_debugPublishCopy'.
         > Could not find com.github.yalantis:ucrop:2.2.1-native.
           Required by:
               Poplar:react-native-image-crop-picker:unspecified

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 19.768 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html

**Comment by forconz** [comment]
【原创】解决React Native报错：Could not find com.github.yalantis:ucrop:2.2.1-native
http://www.blogdaren.com/post-2443.html

参考这篇文章，没解决，不知道这个问题如何解决了

**Comment by lvwangbeta** [comment]
按照官方的配置https://github.com/ivpusic/react-native-image-crop-picker#step-2还是有问题？

**Comment by forconz** [comment]
非常感谢，按你说的链接就配置成功了。

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:installDebug'.
> com.android.builder.testing.api.DeviceException: No connected devices!

这个是另外一个错误了，说明我这个链接提的bug修复了

**Comment by forconz** [comment]
react native真机调试
1、开启手机开发者模式，打开usb调试功能，vivo x20的操作方法为：

进入设置-更多设置-关于手机中，连续快速点击“软件版本号” 7下，会提示"您现在处于开发者模式"，之后进入设置-更多设置-开发者选项中打开USB调试。

2、用数据线连接电脑与手机，关掉手机模拟设备，用 adb devices 命令查看连接设备，若能看到

> List of devices attached 
> 14ed2fcc device

则表示手机连接成功。

3、进入创建好的项目，如

> cd poplar-app

，然后运行 

> react-native

 run-android

如果运行成功，手机上会出现安装界面，点击安装。
vivo的手机稍微恶心一点，快速注册个账号，从短信里复制下密码就可以了。

没有跑服务器的话，poplar会报个错，dimiss all就可以看到界面，登录，注册的界面都能看到。
